AWS_REGION = "ap-northeast-1"
COGNITO_DOMAIN = "https://waf-toggle-ui-demo.auth.ap-northeast-1.amazoncognito.com"
COGNITO_CLIENT_ID = "r54r5gl922l46r2s2ea6nh84b"
API_GATEWAY_URL = "https://82tmqa6o96.execute-api.ap-northeast-1.amazonaws.com/prod/toggle"
COGNITO_REDIRECT_URI = "http://localhost:8501/"
